### ISSUE TITLE
Clarify stack support

### ISSUE THREAD

**Issue by lspitzner** [mvoidex/hsdev#26]
> In order to support stack projects correctly, hsdev and stack executables must be build with same compiler

Please clarify the phrasing. It seems non-trivial to find out what compiler version stack was built with. But that is not what is meant, or is it?

(also, "build"->"built")

**Comment by mvoidex** [comment]
> It seems non-trivial to find out what compiler version stack was built with. But that is not what is meant, or is it?

It is. I've ran into issue with different stacks. I have two stack executables: one was downloaded (x64), and another was installed by `cabal install stack` later (x86). My STACK_ROOT was configured (`stack setup`, `stack build` for projects) with downloaded stack (x64), which had installed separate ghc (x64 too).
 * different `stack path`s returns different package-db paths
 * they also builds into different `snapshot` and `.stack-work/install` folders
 * `ghc-mod` installed by `cabal install ghc-mod` doesn't work with downloaded stack (x64), because its `stack path` returns uncompatible package-dbs (built by different compiler), and `hsdev` runs into same issue.

Using `hsdev` (or `ghc-mod`) built by same compiler as `stack` seems to help.

> (also, "build"->"built")

Thanks, typo

**Comment by mvoidex** [comment]
Could downloaded x64-`stack` be configured to use x86 system ghc?

**Comment by lspitzner** [comment]
ah, thanks for the clarification. though it sounds like it depends on architecture; if `stack` really had different behaviour depending on just the compiler used for compilation, i'd consider that a bug on stack's part. (but it may be the case nonetheless.)

**Comment by mvoidex** [comment]
> Could downloaded x64-stack be configured to use x86 system ghc?

Yeap, it could with `--arch` flag.

**Comment by mvoidex** [comment]
> if stack really had different behaviour depending on just the compiler used for compilation, i'd consider that a bug on stack's part
It seems to have different defaults. `hsdev` (and `ghc-mod`) uses stack commands without specifiyng compiler and arch, so it uses default compiler instead of compatible one.
I'll rewrite this phrase in readme.

**Comment by lspitzner** [comment]
> I'll rewrite this phrase in readme.

thanks!

**Comment by mvoidex** [comment]
Do you have any other suggestions or I could close issue?
