### ISSUE TITLE
'use supress' really suppresses everything

### ISSUE THREAD

**Issue by bscottm** [mvoidex/hsdev#55]
Setting the "log politics" to `use supress` suppresses the `hsdev` startup message with the version number and port number. That completely disables SublimeHaskell's ability to operate. Suggest printing to `stdout` instead of using `simple-log`.

"log politics" always gets a smile from people who see it, because they expect "policies", not "politics".

Also, suggest "suppress" (two "p"-s), since that's the correct spelling. You'll have to keep the current "supress" for backward compatibility.

**Comment by mvoidex** [comment]
Thanks, I'll release new version of simple-log without "politics" :)
And also will update hsdev

> Suggest printing to stdout
You're right

**Comment by bscottm** [comment]
@mvoidex: I'd leave "politics" well enough alone. It's actually an interesting joke that works on multiple levels, whether you're a native English speaker or not. Keep the funny!

**Comment by mvoidex** [comment]
@bscottm, I mean, I'm already preparing new version, and it doesn't have "politics" anymore :)

**Comment by bscottm** [comment]
@mvoidex: I didn't mean for you to remove "politics". I thought it was very funny and so do a lot of my colleagues. Keep the politics! :-)

**Comment by metaleap** [comment]
Just add a flag "--kneeslappers" where all occurrences of `policies` are rewritten as `politics`......   😈

**Comment by mvoidex** [comment]
I meant that it had been removed before you've created this issue
So its gone now :(

`simple-log-0.8.2`: only levels left: one of `trace`, `debug`, `info`, `warning`, `error`, `fatal`
`hsdev-0.2.3.1`: commands `start` and `listen` now accepts `--log-level` instead of `--log-config` and `--config` with with log level, it also sends `Server started at port 4567` to stdout
