### ISSUE TITLE
What's the advantage of hsdev over plain GHCi?

### ISSUE THREAD

**Issue by moodmosaic** [mvoidex/hsdev#82]
Apart from acting as a server, so that it can be consumed by text editors, are there any other advantages?

Have you seen [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) and [Language Server Protocol](https://microsoft.github.io/language-server-protocol/implementors/servers/)?

**Comment by mvoidex** [comment]
I've seen haskell-ide-engine/LSP, but after hsdev was implemented and I haven't compared it with SublimeHaskell/hsdev.

hsdev holds data about all info in memory (last version - in sqlite, so it also doesn't use much memory) and thus can provide some useful data even if source module can't be loaded, or for installed modules that are not dependencies of current file/project etc.

**Comment by nh2** [comment]
I have also tried out `haskell-ide-engine` with with the Sublime [LSP](https://github.com/tomv564/LSP) plugin a couple months ago.

All of it is still rough around the edges (I had to patch a couple things in the LSP plugin), it somewhat works but more work is needed.

I am enthusiastic about HIE+LSP, especially because it's one way to do it for all editors and the promise is that there's as little editor code as possible, and the HIE work is close to GHC (for which improvements will have to be made to make any form of editor integration smoother than it is these days).

I recommend that if hsdev works for you, continue to use it, but also try out and contribute to HIE because it will help Haskell editor integration overall.

**Comment by bscottm** [comment]
@moodmosaic: I've been waiting for it to mature since the last time I tinkered with it. Tempted to look at it again.

**Comment by moodmosaic** [comment]
>I've been waiting for it to mature since the last time I tinkered with it

Right, but is SublimeHaskell (SH) even mature? 😕 I haven't tried `hsdev` outside of SH, but the integration isn't that much reliable.

For example, you can't customize `hlint` (https://github.com/SublimeHaskell/SublimeHaskell/issues/415#issuecomment-375002999), `hdocs` sometimes works, sometimes it doesn't, [and more](https://github.com/SublimeHaskell/SublimeHaskell/issues) 😕

**Comment by nh2** [comment]
@moodmosaic I understand your complaint -- editor tooling in Haskell these days isn't great overall, and right now it needs a lot of effort for those writing it to get it working somewhat OK. Both SH and HIE have troubles to get the user experience smooth, in particular because right now GHC isn't very friendly to integrate with. I think this will improve over time. I'd recommend to try both, file all issues you find, and where possible, also help fixing some.

**Comment by bscottm** [comment]
@moodmosaic: Was that a heavy duty truck that just ran over me or just a really big rock? :-) :-)

(All seriousness aside, that's why I help maintain SH as best as I can. Sometimes I fail, but then again, I'm human. But I do what I can to make the experience better.)

The biggest irritation is the "get the GHC right for your project and `hsdev`" issue. Hard to consistently develop and test when your chasing compiler versions around between your code and the editor backend.

My other nit is that `hsdev` 0.3 didn't develop on a separate branch, but on the `master` branch. That makes adding the `lint_opts` flag support in the 0.2 series impossible.

**Comment by moodmosaic** [comment]
Actually, with `stack build --copy-compiler-tool hsdev hdocs` everything works pretty okay, if you're on the right branch (`hsdev-3` of SH, for `hsdev 3.*`).

I think there are some details that are easy to fix, that could make the overall experience *way* better:
* Don't show a message box if you can't find hsdev from inside Sublime Text (just report to the command line)
* Never show garbage in Sublime Text's command line
* Why `hdocs` isn't always showing up the documentation?
* Clean up the README in SH
* ...

I think I can just schedule some time and try to fix those, as @nh2 very well said. 😅 And I apologize to @mvoidex for spamming this thread for non-hsdev stuff. 🤠

**Comment by bscottm** [comment]
@moodmosaic: Is there any other more appropriate place to have this discussion?

- Got to tell the user that we couldn't find `hsdev`. Reporting to the console (MacOS, Windows -- stderr is basically invisible) isn't really much of an option, since the n00b doesn't even know that the console exists.
- ANSI color escape sequences. Alexandr just fixed this.
- Dunno.
- Absolutely. Better yet, leave the README.md and hack the SH Wiki pages.

**Comment by moodmosaic** [comment]
@bscottm, I think these discussions should be in Sublime Haskell, so I'll open issue(s) there over the weekend. 😅
